# SPDX-License-Identifier: MIT
version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - goconst
    - gocritic
    - gocyclo
    - godox
    - govet
    - gosec
    - importas
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    - nilerr
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - tagliatelle
    - unconvert
    - unused
    - wastedassign
    - whitespace
  settings:
    revive:
      confidence: 0.8 # ignore missing package comments ( xref: https://github.com/golangci/golangci-lint/issues/2610 )
    loggercheck:
      klog: true
      zap: false
      require-string-key: true
      no-printf-like: true
    gosec:
      excludes:
        - G115 # Potential integer overflow when converting between integer types
    importas:
      no-unaliased: false
      alias:
        - pkg: github.com/mercedes-benz/garm-operator/api/v1alpha1
          alias: garmoperatorv1alpha1
        - pkg: github.com/mercedes-benz/garm-operator/api/v1beta1
          alias: garmoperatorv1beta1
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: sigs.k8s.io/controller-runtime
          alias: ctrl
        - pkg: k8s.io/api/admission/v1
          alias: admissionv1
  exclusions:
    rules:
      - linters:
          - revive
        path: 'api/v1alpha1/(.+)_conversion\.go'
        text: "var-naming: don't use underscores in Go names; func (.+)"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/mercedes-benz/garm-operator)
