linters:
  disable-all: true
  fast: false
  enable:
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - godox
    - govet
    - gosec
    - importas
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    - nilerr
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - tagliatelle
    - unconvert
    - unused
    - wastedassign
    - whitespace

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(git.i.mercedes-benz.com/GitHub-Actions/garm-operator)

  goimports:
    local-prefixes: git.i.mercedes-benz.com/GitHub-Actions/garm-operator

  importas:
    no-unaliased: false
    alias:
      - pkg: git.i.mercedes-benz.com/GitHub-Actions/garm-operator/api/v1alpha1
        alias: garmoperatorv1alpha1
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors
      - pkg: sigs.k8s.io/controller-runtime
        alias: ctrl
      - pkg: k8s.io/api/admission/v1
        alias: admissionv1

  loggercheck:
    klog: true
    zap: false
    require-string-key: true
    no-printf-like: true
