# SPDX-License-Identifier: MIT
linters:
  disable-all: true
  fast: false
  enable:
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - godox
    - govet
    - gosec
    - gosimple
    - importas
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    - nilerr
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - tagliatelle
    - unconvert
    - unused
    - wastedassign
    - whitespace
    - kal

linters-settings:
  custom:
    kal:
      type: "module"
      description: KAL is the Kube-API-Linter and lints Kube like APIs based on API conventions and best practices.
      settings:
        linters: {}
        lintersConfig: {}
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/mercedes-benz/garm-operator)

  goimports:
    local-prefixes: github.com/mercedes-benz/garm-operator

  importas:
    no-unaliased: false
    alias:
      - pkg: github.com/mercedes-benz/garm-operator/api/v1alpha1
        alias: garmoperatorv1alpha1
      - pkg: github.com/mercedes-benz/garm-operator/api/v1beta1
        alias: garmoperatorv1beta1
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors
      - pkg: sigs.k8s.io/controller-runtime
        alias: ctrl
      - pkg: k8s.io/api/admission/v1
        alias: admissionv1

  loggercheck:
    klog: true
    zap: false
    require-string-key: true
    no-printf-like: true

  gosec:
    excludes:
      - G115 # Potential integer overflow when converting between integer types

issues:
  exclude-rules:
    # exclude revive warnings for generated code
    - linters:
        - revive
      path: 'api/v1alpha1/(.+)_conversion\.go'
      text: "var-naming: don't use underscores in Go names; func (.+)"
