apiVersion: apps/v1
kind: Deployment
metadata:
  name: garm-operator-controller-manager
  namespace: garm-operator-system
spec:
  template:
    spec:
      containers:
        - name: manager
          command:
            [
              "/dlv",
              "--listen=:2345",
              "--headless=true",
              "--api-version=2",
              "--accept-multiclient",
              "exec",
              "/manager",
              "--wd",
              "/tmp",
              "--",
            ]
          args:
            - --garm-server=http://garm-server.garm-server.svc:9997
            - --garm-username=admin
            - --garm-password=LmrBG1KcBOsDfNKq4cQTGpc0hJ0kejkk
            - --operator-watch-namespace=garm-operator-system
            - --operator-min-idle-runners-age=1m
            - --operator-runner-reconciliation=true
          ports:
            - containerPort: 2345
              name: delve
              protocol: TCP
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
          livenessProbe:
            $patch: delete
          readinessProbe:
            $patch: delete
