# permissions for end users to edit githubcredential.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: githubcredential-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: garm-operator
    app.kubernetes.io/part-of: garm-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubcredential-editor-role
rules:
  - apiGroups:
      - garm-operator.mercedes-benz.com
    resources:
      - githubcredential
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - garm-operator.mercedes-benz.com
    resources:
      - githubcredential/status
    verbs:
      - get
