# permissions for end users to view images.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: image-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: garm-operator
  name: image-viewer-role
rules:
- apiGroups:
  - garm-operator.mercedes-benz.com
  resources:
  - images
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - garm-operator.mercedes-benz.com
  resources:
  - images/status
  verbs:
  - get
