apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: Organization
metadata:
  labels:
    app.kubernetes.io/name: organization
    app.kubernetes.io/instance: organization-int
    app.kubernetes.io/part-of: garm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: garm-operator
  name: github-actions
  namespace: garm-infra-stage-int
spec:
  webhookSecret: "q0g6EU9w788MoTeVz0van50vaxfxRQFE"
  credentialsName: "pida2af"
---
apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: Pool
metadata:
  labels:
    app.kubernetes.io/created-by: garm-operator
    app.kubernetes.io/instance: pool-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pool
    app.kubernetes.io/part-of: garm-operator
  name: kubernetes-pool-small-org-github-actions
  namespace: garm-infra-stage-int
spec:
  githubScopeRef:
    apiGroup: garm-operator.mercedes-benz.com
    kind: Organization
    name: github-actions
  enabled: false
  extraSpecs: '{\"garm_image_type\":\"runner-default\",\"garm_stage\":\"int\"}'
  flavor: small
  forceDeleteRunners: true
  githubRunnerGroup: ""
  image: linux-ubuntu-22.04-amd64
  maxRunners: 2
  minIdleRunners: 1
  osArch: amd64
  osType: linux
  providerName: kubernetes_external
  runnerBootstrapTimeout: 20
  runnerPrefix: "road-runner-k8s-int"
  tags:
    - k8s-int
    - self-hosted
    - Linux
    - x64
---
apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: Pool
metadata:
  labels:
    app.kubernetes.io/created-by: garm-operator
    app.kubernetes.io/instance: pool-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pool
    app.kubernetes.io/part-of: garm-operator
  name: kubernetes-pool-openstack-medium-org-github-actions
  namespace: garm-infra-stage-int
spec:
  githubScopeRef:
    apiGroup: garm-operator.mercedes-benz.com
    kind: Organization
    name: github-actions
  enabled: false
  extraSpecs: '{\"garm_image_type\":\"runner-default\",\"garm_stage\":\"int\"}'
  flavor: m1.medium
  forceDeleteRunners: true
  githubRunnerGroup: ""
  image: runner-default-20230801-13-58-e431482
  maxRunners: 2
  minIdleRunners: 1
  osArch: amd64
  osType: linux
  providerName: os00.fra-prod3
  runnerBootstrapTimeout: 20
  runnerPrefix: "road-runner-os-int"
  tags:
    - openstack-int
    - self-hosted
    - Linux
    - x64
