apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          image: registry-emea.app.corpintra.net/roadrunner/garm-operator:main
          args:
          env:
          - name: GARM_USERNAME
            value: "admin"
          - name: GARM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: garm-cli-password
                key: cliPassword
          - name: GARM_SERVER
            value: "http://garm.garm-infra-stage-int.svc:9997"
          imagePullPolicy: Always
