apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/agent-inject-secret-config: secrets/data/garm-int
        vault.hashicorp.com/role: garm-infra-stage-int_garm-operator-controller-manager
        vault.hashicorp.com/namespace: Action-Runners
        vault.hashicorp.com/agent-inject-secret-garmPassword: 'secrets/data/garm-int'
        vault.hashicorp.com/agent-inject-template-garmPassword: |
          {{- with secret "secrets/data/garm-int" -}}
          {{ .Data.data.cli_password }}
          {{- end -}}
    spec:
      containers:
        - name: manager
          image: registry-emea.app.corpintra.net/roadrunner/garm-operator:feat-rbac
          env:
          - name: GARM_USERNAME
            value: "admin"
          - name: GARM_PASSWORD_SECRET_PATH
            value: "/vault/secrets/garmPassword"
          - name: GARM_SERVER
            value: "http://garm.garm-infra-stage-int.svc:9997"
