{{- if .Values.prometheus.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "garm-operator.fullname" . }}-metrics-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "garm-operator.labels" . | nindent 4 }}
    {{- with .Values.prometheus.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: http
      interval: {{ .Values.prometheus.serviceMonitor.interval | default "30s" }}
  selector:
    matchLabels:
      {{- include "garm-operator.selectorLabels" . | nindent 6 }}
{{- end }}
