apiVersion: garm-operator.mercedes-benz.com/v1beta1
kind: Organization
metadata:
  name: organization-sample
spec:
  webhookSecretRef:
    key: "webhookSecret"
    name: "org-webhook-secret"
  credentialsRef:
    apiGroup: garm-operator.mercedes-benz.com
    kind: GitHubCredentials
    name: github-pat
---
apiVersion: v1
kind: Secret
metadata:
  name: org-webhook-secret
  namespace: garm-operator-system
data:
  webhookSecret: bXlzZWNyZXQ=
