apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: GarmServerConfig
metadata:
  labels:
    app.kubernetes.io/name: garmserverconfig
    app.kubernetes.io/instance: garmserverconfig-sample
    app.kubernetes.io/part-of: garm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: garm-operator
  name: garmserverconfig-sample
spec:
  callbackURL: http://garm-server.garm-server.svc:9997/api/v1/callbacks
  metadataURL: http://garm-server.garm-server.svc:9997/api/v1/metadata
  webhookURL: http://garm-server.garm-server.svc:9997/api/v1/webhook
