apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: Organization
metadata:
  labels:
    app.kubernetes.io/name: organization
    app.kubernetes.io/instance: organization-sample
    app.kubernetes.io/part-of: garm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: garm-operator
  name: github-actions
  namespace: garm-operator-system
spec:
  webhookSecretRef:
    key: "webhookSecret"
    name: "org-webhook-secret"
  credentialsRef:
    apiGroup: garm-operator.mercedes-benz.com
    kind: GitHubCredentials
    name: github-pat
---
apiVersion: v1
kind: Secret
metadata:
  name: org-webhook-secret
  namespace: garm-operator-system
data:
  webhookSecret: bXlzZWNyZXQ=
