apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: Pool
metadata:
  labels:
    app.kubernetes.io/created-by: garm-operator
    app.kubernetes.io/instance: pool-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pool
    app.kubernetes.io/part-of: garm-operator
  name: kubernetes-pool-large
  namespace: garm-operator-system
spec:
  enabled: true
  extra_specs: ""
  flavor: large
  force_delete_runners: false
  github_runner_group: ""
  github_scope: Organization
  github_scope_id: 71c126ee-fc18-424c-a2ce-282966720794
  image: linux-ubuntu-22.04-arm64
  max_runners: 1
  min_idle_runners: 0
  os_arch: arm64
  os_type: linux
  provider_name: kubernetes_external
  runner_bootstrap_timeout: 20
  runner_prefix: ""
  tags:
  - kubernetes
  - linux
  - arm64
  - rthalho
---
apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: Pool
metadata:
  labels:
    app.kubernetes.io/created-by: garm-operator
    app.kubernetes.io/instance: pool-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pool
    app.kubernetes.io/part-of: garm-operator
  name: kubernetes-pool-medium
  namespace: garm-operator-system
spec:
  enabled: true
  extra_specs: ""
  flavor: medium
  force_delete_runners: false
  github_runner_group: ""
  github_scope: Organization
  github_scope_id: 71c126ee-fc18-424c-a2ce-282966720794
  image: linux-ubuntu-22.04-arm64
  max_runners: 1
  min_idle_runners: 0
  os_arch: arm64
  os_type: linux
  provider_name: kubernetes_external
  runner_bootstrap_timeout: 20
  runner_prefix: ""
  tags:
  - kubernetes
  - linux
  - arm64
  - rthalho
---
apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: Pool
metadata:
  labels:
    app.kubernetes.io/created-by: garm-operator
    app.kubernetes.io/instance: pool-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pool
    app.kubernetes.io/part-of: garm-operator
  name: kubernetes-pool-small
  namespace: garm-operator-system
spec:
  enabled: true
  extra_specs: ""
  flavor: small
  force_delete_runners: false
  github_runner_group: ""
  github_scope: Organization
  github_scope_id: 71c126ee-fc18-424c-a2ce-282966720794
  image: linux-ubuntu-22.04-arm64
  max_runners: 1
  min_idle_runners: 0
  os_arch: arm64
  os_type: linux
  provider_name: kubernetes_external
  runner_bootstrap_timeout: 20
  runner_prefix: ""
  tags:
  - kubernetes
  - linux
  - arm64
  - rthalho
