apiVersion: garm-operator.mercedes-benz.com/v1beta1
kind: Runner
metadata:
  labels:
    app.kubernetes.io/name: runner
    app.kubernetes.io/instance: runner-sample
    app.kubernetes.io/part-of: garm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: garm-operator
  name: runner-sample
spec:
  # TODO(user): Add fields here
