apiVersion: garm-operator.mercedes-benz.com/v1beta1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/name: repository
    app.kubernetes.io/instance: repository-sample
    app.kubernetes.io/part-of: garm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: garm-operator
  name: repository-sample
spec:
  # TODO(user): Add fields here
