apiVersion: garm-operator.mercedes-benz.com/v1beta1
kind: Enterprise
metadata:
  name: enterprise-sample
spec:
  credentialsRef:
    apiGroup: garm-operator.mercedes-benz.com
    kind: GitHubCredentials
    name: github-pat
  webhookSecretRef:
    key: "webhookSecret"
    name: "enterprise-webhook-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: enterprise-webhook-secret
  namespace: garm-operator-system
data:
  webhookSecret: bXlzZWNyZXQ=
