apiVersion: garm-operator.mercedes-benz.com/v1beta1
kind: Pool
metadata:
  labels:
    app.kubernetes.io/name: pool
    app.kubernetes.io/instance: pool-sample
    app.kubernetes.io/part-of: garm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: garm-operator
  name: pool-sample
spec:
  # TODO(user): Add fields here
