apiVersion: garm-operator.mercedes-benz.com/v1beta1
kind: Repository
metadata:
  name: repository-sample
spec:
  webhookSecretRef:
    key: "webhookSecret"
    name: "repo-webhook-secret"
  credentialsRef:
    apiGroup: garm-operator.mercedes-benz.com
    kind: GitHubCredentials
    name: github-pat
  owner: "mercedes-benz"
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-webhook-secret
  namespace: garm-operator-system
data:
  webhookSecret: bXlzZWNyZXQ=
