apiVersion: garm-operator.mercedes-benz.com/v1beta1
kind: GarmServerConfig
metadata:
  name: garm-server-config
spec:
  callbackUrl: http://garm-server.garm-server.svc:9997/api/v1/callbacks
  metadataUrl: http://garm-server.garm-server.svc:9997/api/v1/metadata
  webhookUrl: http://garm-server.garm-server.svc:9997/webhook
