//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: MIT

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	params "github.com/cloudbase/garm-provider-common/params"
	garmparams "github.com/cloudbase/garm/params"
	v1beta1 "github.com/mercedes-benz/garm-operator/api/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Enterprise)(nil), (*v1beta1.Enterprise)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Enterprise_To_v1beta1_Enterprise(a.(*Enterprise), b.(*v1beta1.Enterprise), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Enterprise)(nil), (*Enterprise)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Enterprise_To_v1alpha1_Enterprise(a.(*v1beta1.Enterprise), b.(*Enterprise), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EnterpriseList)(nil), (*v1beta1.EnterpriseList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EnterpriseList_To_v1beta1_EnterpriseList(a.(*EnterpriseList), b.(*v1beta1.EnterpriseList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.EnterpriseList)(nil), (*EnterpriseList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EnterpriseList_To_v1alpha1_EnterpriseList(a.(*v1beta1.EnterpriseList), b.(*EnterpriseList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EnterpriseStatus)(nil), (*v1beta1.EnterpriseStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EnterpriseStatus_To_v1beta1_EnterpriseStatus(a.(*EnterpriseStatus), b.(*v1beta1.EnterpriseStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.EnterpriseStatus)(nil), (*EnterpriseStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EnterpriseStatus_To_v1alpha1_EnterpriseStatus(a.(*v1beta1.EnterpriseStatus), b.(*EnterpriseStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Image)(nil), (*v1beta1.Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Image_To_v1beta1_Image(a.(*Image), b.(*v1beta1.Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Image)(nil), (*Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Image_To_v1alpha1_Image(a.(*v1beta1.Image), b.(*Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ImageList)(nil), (*v1beta1.ImageList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ImageList_To_v1beta1_ImageList(a.(*ImageList), b.(*v1beta1.ImageList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ImageList)(nil), (*ImageList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ImageList_To_v1alpha1_ImageList(a.(*v1beta1.ImageList), b.(*ImageList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ImageSpec)(nil), (*v1beta1.ImageSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ImageSpec_To_v1beta1_ImageSpec(a.(*ImageSpec), b.(*v1beta1.ImageSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ImageSpec)(nil), (*ImageSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ImageSpec_To_v1alpha1_ImageSpec(a.(*v1beta1.ImageSpec), b.(*ImageSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ImageStatus)(nil), (*v1beta1.ImageStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ImageStatus_To_v1beta1_ImageStatus(a.(*ImageStatus), b.(*v1beta1.ImageStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ImageStatus)(nil), (*ImageStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ImageStatus_To_v1alpha1_ImageStatus(a.(*v1beta1.ImageStatus), b.(*ImageStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ImageValidator)(nil), (*v1beta1.ImageValidator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ImageValidator_To_v1beta1_ImageValidator(a.(*ImageValidator), b.(*v1beta1.ImageValidator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ImageValidator)(nil), (*ImageValidator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ImageValidator_To_v1alpha1_ImageValidator(a.(*v1beta1.ImageValidator), b.(*ImageValidator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Organization)(nil), (*v1beta1.Organization)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Organization_To_v1beta1_Organization(a.(*Organization), b.(*v1beta1.Organization), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Organization)(nil), (*Organization)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Organization_To_v1alpha1_Organization(a.(*v1beta1.Organization), b.(*Organization), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrganizationList)(nil), (*v1beta1.OrganizationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrganizationList_To_v1beta1_OrganizationList(a.(*OrganizationList), b.(*v1beta1.OrganizationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.OrganizationList)(nil), (*OrganizationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OrganizationList_To_v1alpha1_OrganizationList(a.(*v1beta1.OrganizationList), b.(*OrganizationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrganizationStatus)(nil), (*v1beta1.OrganizationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrganizationStatus_To_v1beta1_OrganizationStatus(a.(*OrganizationStatus), b.(*v1beta1.OrganizationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.OrganizationStatus)(nil), (*OrganizationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OrganizationStatus_To_v1alpha1_OrganizationStatus(a.(*v1beta1.OrganizationStatus), b.(*OrganizationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Pool)(nil), (*v1beta1.Pool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Pool_To_v1beta1_Pool(a.(*Pool), b.(*v1beta1.Pool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Pool)(nil), (*Pool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Pool_To_v1alpha1_Pool(a.(*v1beta1.Pool), b.(*Pool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PoolList)(nil), (*v1beta1.PoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PoolList_To_v1beta1_PoolList(a.(*PoolList), b.(*v1beta1.PoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PoolList)(nil), (*PoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PoolList_To_v1alpha1_PoolList(a.(*v1beta1.PoolList), b.(*PoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PoolSpec)(nil), (*v1beta1.PoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PoolSpec_To_v1beta1_PoolSpec(a.(*PoolSpec), b.(*v1beta1.PoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PoolSpec)(nil), (*PoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PoolSpec_To_v1alpha1_PoolSpec(a.(*v1beta1.PoolSpec), b.(*PoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PoolStatus)(nil), (*v1beta1.PoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PoolStatus_To_v1beta1_PoolStatus(a.(*PoolStatus), b.(*v1beta1.PoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PoolStatus)(nil), (*PoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PoolStatus_To_v1alpha1_PoolStatus(a.(*v1beta1.PoolStatus), b.(*PoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PoolValidator)(nil), (*v1beta1.PoolValidator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PoolValidator_To_v1beta1_PoolValidator(a.(*PoolValidator), b.(*v1beta1.PoolValidator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PoolValidator)(nil), (*PoolValidator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PoolValidator_To_v1alpha1_PoolValidator(a.(*v1beta1.PoolValidator), b.(*PoolValidator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Repository)(nil), (*v1beta1.Repository)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Repository_To_v1beta1_Repository(a.(*Repository), b.(*v1beta1.Repository), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Repository)(nil), (*Repository)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Repository_To_v1alpha1_Repository(a.(*v1beta1.Repository), b.(*Repository), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RepositoryList)(nil), (*v1beta1.RepositoryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RepositoryList_To_v1beta1_RepositoryList(a.(*RepositoryList), b.(*v1beta1.RepositoryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RepositoryList)(nil), (*RepositoryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RepositoryList_To_v1alpha1_RepositoryList(a.(*v1beta1.RepositoryList), b.(*RepositoryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RepositoryStatus)(nil), (*v1beta1.RepositoryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RepositoryStatus_To_v1beta1_RepositoryStatus(a.(*RepositoryStatus), b.(*v1beta1.RepositoryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RepositoryStatus)(nil), (*RepositoryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RepositoryStatus_To_v1alpha1_RepositoryStatus(a.(*v1beta1.RepositoryStatus), b.(*RepositoryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RepositoryValidator)(nil), (*v1beta1.RepositoryValidator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RepositoryValidator_To_v1beta1_RepositoryValidator(a.(*RepositoryValidator), b.(*v1beta1.RepositoryValidator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RepositoryValidator)(nil), (*RepositoryValidator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RepositoryValidator_To_v1alpha1_RepositoryValidator(a.(*v1beta1.RepositoryValidator), b.(*RepositoryValidator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Runner)(nil), (*v1beta1.Runner)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Runner_To_v1beta1_Runner(a.(*Runner), b.(*v1beta1.Runner), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Runner)(nil), (*Runner)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Runner_To_v1alpha1_Runner(a.(*v1beta1.Runner), b.(*Runner), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RunnerList)(nil), (*v1beta1.RunnerList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RunnerList_To_v1beta1_RunnerList(a.(*RunnerList), b.(*v1beta1.RunnerList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RunnerList)(nil), (*RunnerList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RunnerList_To_v1alpha1_RunnerList(a.(*v1beta1.RunnerList), b.(*RunnerList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RunnerSpec)(nil), (*v1beta1.RunnerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RunnerSpec_To_v1beta1_RunnerSpec(a.(*RunnerSpec), b.(*v1beta1.RunnerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RunnerSpec)(nil), (*RunnerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RunnerSpec_To_v1alpha1_RunnerSpec(a.(*v1beta1.RunnerSpec), b.(*RunnerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RunnerStatus)(nil), (*v1beta1.RunnerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RunnerStatus_To_v1beta1_RunnerStatus(a.(*RunnerStatus), b.(*v1beta1.RunnerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RunnerStatus)(nil), (*RunnerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RunnerStatus_To_v1alpha1_RunnerStatus(a.(*v1beta1.RunnerStatus), b.(*RunnerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretRef)(nil), (*v1beta1.SecretRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecretRef_To_v1beta1_SecretRef(a.(*SecretRef), b.(*v1beta1.SecretRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SecretRef)(nil), (*SecretRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SecretRef_To_v1alpha1_SecretRef(a.(*v1beta1.SecretRef), b.(*SecretRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*EnterpriseSpec)(nil), (*v1beta1.EnterpriseSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EnterpriseSpec_To_v1beta1_EnterpriseSpec(a.(*EnterpriseSpec), b.(*v1beta1.EnterpriseSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*OrganizationSpec)(nil), (*v1beta1.OrganizationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrganizationSpec_To_v1beta1_OrganizationSpec(a.(*OrganizationSpec), b.(*v1beta1.OrganizationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*RepositorySpec)(nil), (*v1beta1.RepositorySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RepositorySpec_To_v1beta1_RepositorySpec(a.(*RepositorySpec), b.(*v1beta1.RepositorySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.EnterpriseSpec)(nil), (*EnterpriseSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EnterpriseSpec_To_v1alpha1_EnterpriseSpec(a.(*v1beta1.EnterpriseSpec), b.(*EnterpriseSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.OrganizationSpec)(nil), (*OrganizationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OrganizationSpec_To_v1alpha1_OrganizationSpec(a.(*v1beta1.OrganizationSpec), b.(*OrganizationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.RepositorySpec)(nil), (*RepositorySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RepositorySpec_To_v1alpha1_RepositorySpec(a.(*v1beta1.RepositorySpec), b.(*RepositorySpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Enterprise_To_v1beta1_Enterprise(in *Enterprise, out *v1beta1.Enterprise, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_EnterpriseSpec_To_v1beta1_EnterpriseSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_EnterpriseStatus_To_v1beta1_EnterpriseStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Enterprise_To_v1beta1_Enterprise is an autogenerated conversion function.
func Convert_v1alpha1_Enterprise_To_v1beta1_Enterprise(in *Enterprise, out *v1beta1.Enterprise, s conversion.Scope) error {
	return autoConvert_v1alpha1_Enterprise_To_v1beta1_Enterprise(in, out, s)
}

func autoConvert_v1beta1_Enterprise_To_v1alpha1_Enterprise(in *v1beta1.Enterprise, out *Enterprise, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_EnterpriseSpec_To_v1alpha1_EnterpriseSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_EnterpriseStatus_To_v1alpha1_EnterpriseStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Enterprise_To_v1alpha1_Enterprise is an autogenerated conversion function.
func Convert_v1beta1_Enterprise_To_v1alpha1_Enterprise(in *v1beta1.Enterprise, out *Enterprise, s conversion.Scope) error {
	return autoConvert_v1beta1_Enterprise_To_v1alpha1_Enterprise(in, out, s)
}

func autoConvert_v1alpha1_EnterpriseList_To_v1beta1_EnterpriseList(in *EnterpriseList, out *v1beta1.EnterpriseList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.Enterprise, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Enterprise_To_v1beta1_Enterprise(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_EnterpriseList_To_v1beta1_EnterpriseList is an autogenerated conversion function.
func Convert_v1alpha1_EnterpriseList_To_v1beta1_EnterpriseList(in *EnterpriseList, out *v1beta1.EnterpriseList, s conversion.Scope) error {
	return autoConvert_v1alpha1_EnterpriseList_To_v1beta1_EnterpriseList(in, out, s)
}

func autoConvert_v1beta1_EnterpriseList_To_v1alpha1_EnterpriseList(in *v1beta1.EnterpriseList, out *EnterpriseList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Enterprise, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Enterprise_To_v1alpha1_Enterprise(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_EnterpriseList_To_v1alpha1_EnterpriseList is an autogenerated conversion function.
func Convert_v1beta1_EnterpriseList_To_v1alpha1_EnterpriseList(in *v1beta1.EnterpriseList, out *EnterpriseList, s conversion.Scope) error {
	return autoConvert_v1beta1_EnterpriseList_To_v1alpha1_EnterpriseList(in, out, s)
}

func autoConvert_v1alpha1_EnterpriseSpec_To_v1beta1_EnterpriseSpec(in *EnterpriseSpec, out *v1beta1.EnterpriseSpec, s conversion.Scope) error {
	// WARNING: in.CredentialsName requires manual conversion: does not exist in peer-type
	if err := Convert_v1alpha1_SecretRef_To_v1beta1_SecretRef(&in.WebhookSecretRef, &out.WebhookSecretRef, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_EnterpriseSpec_To_v1alpha1_EnterpriseSpec(in *v1beta1.EnterpriseSpec, out *EnterpriseSpec, s conversion.Scope) error {
	// WARNING: in.CredentialsRef requires manual conversion: does not exist in peer-type
	if err := Convert_v1beta1_SecretRef_To_v1alpha1_SecretRef(&in.WebhookSecretRef, &out.WebhookSecretRef, s); err != nil {
		return err
	}
	// WARNING: in.PoolBalancerType requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_EnterpriseStatus_To_v1beta1_EnterpriseStatus(in *EnterpriseStatus, out *v1beta1.EnterpriseStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_EnterpriseStatus_To_v1beta1_EnterpriseStatus is an autogenerated conversion function.
func Convert_v1alpha1_EnterpriseStatus_To_v1beta1_EnterpriseStatus(in *EnterpriseStatus, out *v1beta1.EnterpriseStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_EnterpriseStatus_To_v1beta1_EnterpriseStatus(in, out, s)
}

func autoConvert_v1beta1_EnterpriseStatus_To_v1alpha1_EnterpriseStatus(in *v1beta1.EnterpriseStatus, out *EnterpriseStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_EnterpriseStatus_To_v1alpha1_EnterpriseStatus is an autogenerated conversion function.
func Convert_v1beta1_EnterpriseStatus_To_v1alpha1_EnterpriseStatus(in *v1beta1.EnterpriseStatus, out *EnterpriseStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_EnterpriseStatus_To_v1alpha1_EnterpriseStatus(in, out, s)
}

func autoConvert_v1alpha1_Image_To_v1beta1_Image(in *Image, out *v1beta1.Image, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ImageSpec_To_v1beta1_ImageSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ImageStatus_To_v1beta1_ImageStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Image_To_v1beta1_Image is an autogenerated conversion function.
func Convert_v1alpha1_Image_To_v1beta1_Image(in *Image, out *v1beta1.Image, s conversion.Scope) error {
	return autoConvert_v1alpha1_Image_To_v1beta1_Image(in, out, s)
}

func autoConvert_v1beta1_Image_To_v1alpha1_Image(in *v1beta1.Image, out *Image, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_ImageSpec_To_v1alpha1_ImageSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_ImageStatus_To_v1alpha1_ImageStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Image_To_v1alpha1_Image is an autogenerated conversion function.
func Convert_v1beta1_Image_To_v1alpha1_Image(in *v1beta1.Image, out *Image, s conversion.Scope) error {
	return autoConvert_v1beta1_Image_To_v1alpha1_Image(in, out, s)
}

func autoConvert_v1alpha1_ImageList_To_v1beta1_ImageList(in *ImageList, out *v1beta1.ImageList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.Image)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ImageList_To_v1beta1_ImageList is an autogenerated conversion function.
func Convert_v1alpha1_ImageList_To_v1beta1_ImageList(in *ImageList, out *v1beta1.ImageList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ImageList_To_v1beta1_ImageList(in, out, s)
}

func autoConvert_v1beta1_ImageList_To_v1alpha1_ImageList(in *v1beta1.ImageList, out *ImageList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Image)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_ImageList_To_v1alpha1_ImageList is an autogenerated conversion function.
func Convert_v1beta1_ImageList_To_v1alpha1_ImageList(in *v1beta1.ImageList, out *ImageList, s conversion.Scope) error {
	return autoConvert_v1beta1_ImageList_To_v1alpha1_ImageList(in, out, s)
}

func autoConvert_v1alpha1_ImageSpec_To_v1beta1_ImageSpec(in *ImageSpec, out *v1beta1.ImageSpec, s conversion.Scope) error {
	out.Tag = in.Tag
	return nil
}

// Convert_v1alpha1_ImageSpec_To_v1beta1_ImageSpec is an autogenerated conversion function.
func Convert_v1alpha1_ImageSpec_To_v1beta1_ImageSpec(in *ImageSpec, out *v1beta1.ImageSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ImageSpec_To_v1beta1_ImageSpec(in, out, s)
}

func autoConvert_v1beta1_ImageSpec_To_v1alpha1_ImageSpec(in *v1beta1.ImageSpec, out *ImageSpec, s conversion.Scope) error {
	out.Tag = in.Tag
	return nil
}

// Convert_v1beta1_ImageSpec_To_v1alpha1_ImageSpec is an autogenerated conversion function.
func Convert_v1beta1_ImageSpec_To_v1alpha1_ImageSpec(in *v1beta1.ImageSpec, out *ImageSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_ImageSpec_To_v1alpha1_ImageSpec(in, out, s)
}

func autoConvert_v1alpha1_ImageStatus_To_v1beta1_ImageStatus(in *ImageStatus, out *v1beta1.ImageStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ImageStatus_To_v1beta1_ImageStatus is an autogenerated conversion function.
func Convert_v1alpha1_ImageStatus_To_v1beta1_ImageStatus(in *ImageStatus, out *v1beta1.ImageStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ImageStatus_To_v1beta1_ImageStatus(in, out, s)
}

func autoConvert_v1beta1_ImageStatus_To_v1alpha1_ImageStatus(in *v1beta1.ImageStatus, out *ImageStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_ImageStatus_To_v1alpha1_ImageStatus is an autogenerated conversion function.
func Convert_v1beta1_ImageStatus_To_v1alpha1_ImageStatus(in *v1beta1.ImageStatus, out *ImageStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_ImageStatus_To_v1alpha1_ImageStatus(in, out, s)
}

func autoConvert_v1alpha1_ImageValidator_To_v1beta1_ImageValidator(in *ImageValidator, out *v1beta1.ImageValidator, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ImageValidator_To_v1beta1_ImageValidator is an autogenerated conversion function.
func Convert_v1alpha1_ImageValidator_To_v1beta1_ImageValidator(in *ImageValidator, out *v1beta1.ImageValidator, s conversion.Scope) error {
	return autoConvert_v1alpha1_ImageValidator_To_v1beta1_ImageValidator(in, out, s)
}

func autoConvert_v1beta1_ImageValidator_To_v1alpha1_ImageValidator(in *v1beta1.ImageValidator, out *ImageValidator, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_ImageValidator_To_v1alpha1_ImageValidator is an autogenerated conversion function.
func Convert_v1beta1_ImageValidator_To_v1alpha1_ImageValidator(in *v1beta1.ImageValidator, out *ImageValidator, s conversion.Scope) error {
	return autoConvert_v1beta1_ImageValidator_To_v1alpha1_ImageValidator(in, out, s)
}

func autoConvert_v1alpha1_Organization_To_v1beta1_Organization(in *Organization, out *v1beta1.Organization, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_OrganizationSpec_To_v1beta1_OrganizationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_OrganizationStatus_To_v1beta1_OrganizationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Organization_To_v1beta1_Organization is an autogenerated conversion function.
func Convert_v1alpha1_Organization_To_v1beta1_Organization(in *Organization, out *v1beta1.Organization, s conversion.Scope) error {
	return autoConvert_v1alpha1_Organization_To_v1beta1_Organization(in, out, s)
}

func autoConvert_v1beta1_Organization_To_v1alpha1_Organization(in *v1beta1.Organization, out *Organization, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_OrganizationSpec_To_v1alpha1_OrganizationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OrganizationStatus_To_v1alpha1_OrganizationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Organization_To_v1alpha1_Organization is an autogenerated conversion function.
func Convert_v1beta1_Organization_To_v1alpha1_Organization(in *v1beta1.Organization, out *Organization, s conversion.Scope) error {
	return autoConvert_v1beta1_Organization_To_v1alpha1_Organization(in, out, s)
}

func autoConvert_v1alpha1_OrganizationList_To_v1beta1_OrganizationList(in *OrganizationList, out *v1beta1.OrganizationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.Organization, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Organization_To_v1beta1_Organization(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_OrganizationList_To_v1beta1_OrganizationList is an autogenerated conversion function.
func Convert_v1alpha1_OrganizationList_To_v1beta1_OrganizationList(in *OrganizationList, out *v1beta1.OrganizationList, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrganizationList_To_v1beta1_OrganizationList(in, out, s)
}

func autoConvert_v1beta1_OrganizationList_To_v1alpha1_OrganizationList(in *v1beta1.OrganizationList, out *OrganizationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Organization, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Organization_To_v1alpha1_Organization(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_OrganizationList_To_v1alpha1_OrganizationList is an autogenerated conversion function.
func Convert_v1beta1_OrganizationList_To_v1alpha1_OrganizationList(in *v1beta1.OrganizationList, out *OrganizationList, s conversion.Scope) error {
	return autoConvert_v1beta1_OrganizationList_To_v1alpha1_OrganizationList(in, out, s)
}

func autoConvert_v1alpha1_OrganizationSpec_To_v1beta1_OrganizationSpec(in *OrganizationSpec, out *v1beta1.OrganizationSpec, s conversion.Scope) error {
	// WARNING: in.CredentialsName requires manual conversion: does not exist in peer-type
	if err := Convert_v1alpha1_SecretRef_To_v1beta1_SecretRef(&in.WebhookSecretRef, &out.WebhookSecretRef, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_OrganizationSpec_To_v1alpha1_OrganizationSpec(in *v1beta1.OrganizationSpec, out *OrganizationSpec, s conversion.Scope) error {
	// WARNING: in.CredentialsRef requires manual conversion: does not exist in peer-type
	if err := Convert_v1beta1_SecretRef_To_v1alpha1_SecretRef(&in.WebhookSecretRef, &out.WebhookSecretRef, s); err != nil {
		return err
	}
	// WARNING: in.PoolBalancerType requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_OrganizationStatus_To_v1beta1_OrganizationStatus(in *OrganizationStatus, out *v1beta1.OrganizationStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_OrganizationStatus_To_v1beta1_OrganizationStatus is an autogenerated conversion function.
func Convert_v1alpha1_OrganizationStatus_To_v1beta1_OrganizationStatus(in *OrganizationStatus, out *v1beta1.OrganizationStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrganizationStatus_To_v1beta1_OrganizationStatus(in, out, s)
}

func autoConvert_v1beta1_OrganizationStatus_To_v1alpha1_OrganizationStatus(in *v1beta1.OrganizationStatus, out *OrganizationStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_OrganizationStatus_To_v1alpha1_OrganizationStatus is an autogenerated conversion function.
func Convert_v1beta1_OrganizationStatus_To_v1alpha1_OrganizationStatus(in *v1beta1.OrganizationStatus, out *OrganizationStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_OrganizationStatus_To_v1alpha1_OrganizationStatus(in, out, s)
}

func autoConvert_v1alpha1_Pool_To_v1beta1_Pool(in *Pool, out *v1beta1.Pool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PoolSpec_To_v1beta1_PoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PoolStatus_To_v1beta1_PoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Pool_To_v1beta1_Pool is an autogenerated conversion function.
func Convert_v1alpha1_Pool_To_v1beta1_Pool(in *Pool, out *v1beta1.Pool, s conversion.Scope) error {
	return autoConvert_v1alpha1_Pool_To_v1beta1_Pool(in, out, s)
}

func autoConvert_v1beta1_Pool_To_v1alpha1_Pool(in *v1beta1.Pool, out *Pool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_PoolSpec_To_v1alpha1_PoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_PoolStatus_To_v1alpha1_PoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Pool_To_v1alpha1_Pool is an autogenerated conversion function.
func Convert_v1beta1_Pool_To_v1alpha1_Pool(in *v1beta1.Pool, out *Pool, s conversion.Scope) error {
	return autoConvert_v1beta1_Pool_To_v1alpha1_Pool(in, out, s)
}

func autoConvert_v1alpha1_PoolList_To_v1beta1_PoolList(in *PoolList, out *v1beta1.PoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.Pool)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PoolList_To_v1beta1_PoolList is an autogenerated conversion function.
func Convert_v1alpha1_PoolList_To_v1beta1_PoolList(in *PoolList, out *v1beta1.PoolList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PoolList_To_v1beta1_PoolList(in, out, s)
}

func autoConvert_v1beta1_PoolList_To_v1alpha1_PoolList(in *v1beta1.PoolList, out *PoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Pool)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_PoolList_To_v1alpha1_PoolList is an autogenerated conversion function.
func Convert_v1beta1_PoolList_To_v1alpha1_PoolList(in *v1beta1.PoolList, out *PoolList, s conversion.Scope) error {
	return autoConvert_v1beta1_PoolList_To_v1alpha1_PoolList(in, out, s)
}

func autoConvert_v1alpha1_PoolSpec_To_v1beta1_PoolSpec(in *PoolSpec, out *v1beta1.PoolSpec, s conversion.Scope) error {
	out.GitHubScopeRef = in.GitHubScopeRef
	out.ProviderName = in.ProviderName
	out.MaxRunners = in.MaxRunners
	out.MinIdleRunners = in.MinIdleRunners
	out.Flavor = in.Flavor
	out.OSType = params.OSType(in.OSType)
	out.OSArch = params.OSArch(in.OSArch)
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.Enabled = in.Enabled
	out.RunnerBootstrapTimeout = in.RunnerBootstrapTimeout
	out.ImageName = in.ImageName
	out.ExtraSpecs = in.ExtraSpecs
	out.GitHubRunnerGroup = in.GitHubRunnerGroup
	out.RunnerPrefix = in.RunnerPrefix
	return nil
}

// Convert_v1alpha1_PoolSpec_To_v1beta1_PoolSpec is an autogenerated conversion function.
func Convert_v1alpha1_PoolSpec_To_v1beta1_PoolSpec(in *PoolSpec, out *v1beta1.PoolSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PoolSpec_To_v1beta1_PoolSpec(in, out, s)
}

func autoConvert_v1beta1_PoolSpec_To_v1alpha1_PoolSpec(in *v1beta1.PoolSpec, out *PoolSpec, s conversion.Scope) error {
	out.GitHubScopeRef = in.GitHubScopeRef
	out.ProviderName = in.ProviderName
	out.MaxRunners = in.MaxRunners
	out.MinIdleRunners = in.MinIdleRunners
	out.Flavor = in.Flavor
	out.OSType = params.OSType(in.OSType)
	out.OSArch = params.OSArch(in.OSArch)
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.Enabled = in.Enabled
	out.RunnerBootstrapTimeout = in.RunnerBootstrapTimeout
	out.ImageName = in.ImageName
	out.ExtraSpecs = in.ExtraSpecs
	out.GitHubRunnerGroup = in.GitHubRunnerGroup
	out.RunnerPrefix = in.RunnerPrefix
	return nil
}

// Convert_v1beta1_PoolSpec_To_v1alpha1_PoolSpec is an autogenerated conversion function.
func Convert_v1beta1_PoolSpec_To_v1alpha1_PoolSpec(in *v1beta1.PoolSpec, out *PoolSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_PoolSpec_To_v1alpha1_PoolSpec(in, out, s)
}

func autoConvert_v1alpha1_PoolStatus_To_v1beta1_PoolStatus(in *PoolStatus, out *v1beta1.PoolStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.LongRunningIdleRunners = in.LongRunningIdleRunners
	out.Selector = in.Selector
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_PoolStatus_To_v1beta1_PoolStatus is an autogenerated conversion function.
func Convert_v1alpha1_PoolStatus_To_v1beta1_PoolStatus(in *PoolStatus, out *v1beta1.PoolStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PoolStatus_To_v1beta1_PoolStatus(in, out, s)
}

func autoConvert_v1beta1_PoolStatus_To_v1alpha1_PoolStatus(in *v1beta1.PoolStatus, out *PoolStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.LongRunningIdleRunners = in.LongRunningIdleRunners
	out.Selector = in.Selector
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_PoolStatus_To_v1alpha1_PoolStatus is an autogenerated conversion function.
func Convert_v1beta1_PoolStatus_To_v1alpha1_PoolStatus(in *v1beta1.PoolStatus, out *PoolStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_PoolStatus_To_v1alpha1_PoolStatus(in, out, s)
}

func autoConvert_v1alpha1_PoolValidator_To_v1beta1_PoolValidator(in *PoolValidator, out *v1beta1.PoolValidator, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_PoolValidator_To_v1beta1_PoolValidator is an autogenerated conversion function.
func Convert_v1alpha1_PoolValidator_To_v1beta1_PoolValidator(in *PoolValidator, out *v1beta1.PoolValidator, s conversion.Scope) error {
	return autoConvert_v1alpha1_PoolValidator_To_v1beta1_PoolValidator(in, out, s)
}

func autoConvert_v1beta1_PoolValidator_To_v1alpha1_PoolValidator(in *v1beta1.PoolValidator, out *PoolValidator, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_PoolValidator_To_v1alpha1_PoolValidator is an autogenerated conversion function.
func Convert_v1beta1_PoolValidator_To_v1alpha1_PoolValidator(in *v1beta1.PoolValidator, out *PoolValidator, s conversion.Scope) error {
	return autoConvert_v1beta1_PoolValidator_To_v1alpha1_PoolValidator(in, out, s)
}

func autoConvert_v1alpha1_Repository_To_v1beta1_Repository(in *Repository, out *v1beta1.Repository, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RepositorySpec_To_v1beta1_RepositorySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RepositoryStatus_To_v1beta1_RepositoryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Repository_To_v1beta1_Repository is an autogenerated conversion function.
func Convert_v1alpha1_Repository_To_v1beta1_Repository(in *Repository, out *v1beta1.Repository, s conversion.Scope) error {
	return autoConvert_v1alpha1_Repository_To_v1beta1_Repository(in, out, s)
}

func autoConvert_v1beta1_Repository_To_v1alpha1_Repository(in *v1beta1.Repository, out *Repository, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_RepositorySpec_To_v1alpha1_RepositorySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RepositoryStatus_To_v1alpha1_RepositoryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Repository_To_v1alpha1_Repository is an autogenerated conversion function.
func Convert_v1beta1_Repository_To_v1alpha1_Repository(in *v1beta1.Repository, out *Repository, s conversion.Scope) error {
	return autoConvert_v1beta1_Repository_To_v1alpha1_Repository(in, out, s)
}

func autoConvert_v1alpha1_RepositoryList_To_v1beta1_RepositoryList(in *RepositoryList, out *v1beta1.RepositoryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.Repository, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Repository_To_v1beta1_Repository(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_RepositoryList_To_v1beta1_RepositoryList is an autogenerated conversion function.
func Convert_v1alpha1_RepositoryList_To_v1beta1_RepositoryList(in *RepositoryList, out *v1beta1.RepositoryList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RepositoryList_To_v1beta1_RepositoryList(in, out, s)
}

func autoConvert_v1beta1_RepositoryList_To_v1alpha1_RepositoryList(in *v1beta1.RepositoryList, out *RepositoryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Repository, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Repository_To_v1alpha1_Repository(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_RepositoryList_To_v1alpha1_RepositoryList is an autogenerated conversion function.
func Convert_v1beta1_RepositoryList_To_v1alpha1_RepositoryList(in *v1beta1.RepositoryList, out *RepositoryList, s conversion.Scope) error {
	return autoConvert_v1beta1_RepositoryList_To_v1alpha1_RepositoryList(in, out, s)
}

func autoConvert_v1alpha1_RepositorySpec_To_v1beta1_RepositorySpec(in *RepositorySpec, out *v1beta1.RepositorySpec, s conversion.Scope) error {
	// WARNING: in.CredentialsName requires manual conversion: does not exist in peer-type
	out.Owner = in.Owner
	if err := Convert_v1alpha1_SecretRef_To_v1beta1_SecretRef(&in.WebhookSecretRef, &out.WebhookSecretRef, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_RepositorySpec_To_v1alpha1_RepositorySpec(in *v1beta1.RepositorySpec, out *RepositorySpec, s conversion.Scope) error {
	// WARNING: in.CredentialsRef requires manual conversion: does not exist in peer-type
	out.Owner = in.Owner
	if err := Convert_v1beta1_SecretRef_To_v1alpha1_SecretRef(&in.WebhookSecretRef, &out.WebhookSecretRef, s); err != nil {
		return err
	}
	// WARNING: in.PoolBalancerType requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_RepositoryStatus_To_v1beta1_RepositoryStatus(in *RepositoryStatus, out *v1beta1.RepositoryStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_RepositoryStatus_To_v1beta1_RepositoryStatus is an autogenerated conversion function.
func Convert_v1alpha1_RepositoryStatus_To_v1beta1_RepositoryStatus(in *RepositoryStatus, out *v1beta1.RepositoryStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RepositoryStatus_To_v1beta1_RepositoryStatus(in, out, s)
}

func autoConvert_v1beta1_RepositoryStatus_To_v1alpha1_RepositoryStatus(in *v1beta1.RepositoryStatus, out *RepositoryStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_RepositoryStatus_To_v1alpha1_RepositoryStatus is an autogenerated conversion function.
func Convert_v1beta1_RepositoryStatus_To_v1alpha1_RepositoryStatus(in *v1beta1.RepositoryStatus, out *RepositoryStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_RepositoryStatus_To_v1alpha1_RepositoryStatus(in, out, s)
}

func autoConvert_v1alpha1_RepositoryValidator_To_v1beta1_RepositoryValidator(in *RepositoryValidator, out *v1beta1.RepositoryValidator, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_RepositoryValidator_To_v1beta1_RepositoryValidator is an autogenerated conversion function.
func Convert_v1alpha1_RepositoryValidator_To_v1beta1_RepositoryValidator(in *RepositoryValidator, out *v1beta1.RepositoryValidator, s conversion.Scope) error {
	return autoConvert_v1alpha1_RepositoryValidator_To_v1beta1_RepositoryValidator(in, out, s)
}

func autoConvert_v1beta1_RepositoryValidator_To_v1alpha1_RepositoryValidator(in *v1beta1.RepositoryValidator, out *RepositoryValidator, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_RepositoryValidator_To_v1alpha1_RepositoryValidator is an autogenerated conversion function.
func Convert_v1beta1_RepositoryValidator_To_v1alpha1_RepositoryValidator(in *v1beta1.RepositoryValidator, out *RepositoryValidator, s conversion.Scope) error {
	return autoConvert_v1beta1_RepositoryValidator_To_v1alpha1_RepositoryValidator(in, out, s)
}

func autoConvert_v1alpha1_Runner_To_v1beta1_Runner(in *Runner, out *v1beta1.Runner, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RunnerSpec_To_v1beta1_RunnerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RunnerStatus_To_v1beta1_RunnerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Runner_To_v1beta1_Runner is an autogenerated conversion function.
func Convert_v1alpha1_Runner_To_v1beta1_Runner(in *Runner, out *v1beta1.Runner, s conversion.Scope) error {
	return autoConvert_v1alpha1_Runner_To_v1beta1_Runner(in, out, s)
}

func autoConvert_v1beta1_Runner_To_v1alpha1_Runner(in *v1beta1.Runner, out *Runner, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_RunnerSpec_To_v1alpha1_RunnerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RunnerStatus_To_v1alpha1_RunnerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Runner_To_v1alpha1_Runner is an autogenerated conversion function.
func Convert_v1beta1_Runner_To_v1alpha1_Runner(in *v1beta1.Runner, out *Runner, s conversion.Scope) error {
	return autoConvert_v1beta1_Runner_To_v1alpha1_Runner(in, out, s)
}

func autoConvert_v1alpha1_RunnerList_To_v1beta1_RunnerList(in *RunnerList, out *v1beta1.RunnerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.Runner)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_RunnerList_To_v1beta1_RunnerList is an autogenerated conversion function.
func Convert_v1alpha1_RunnerList_To_v1beta1_RunnerList(in *RunnerList, out *v1beta1.RunnerList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RunnerList_To_v1beta1_RunnerList(in, out, s)
}

func autoConvert_v1beta1_RunnerList_To_v1alpha1_RunnerList(in *v1beta1.RunnerList, out *RunnerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Runner)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_RunnerList_To_v1alpha1_RunnerList is an autogenerated conversion function.
func Convert_v1beta1_RunnerList_To_v1alpha1_RunnerList(in *v1beta1.RunnerList, out *RunnerList, s conversion.Scope) error {
	return autoConvert_v1beta1_RunnerList_To_v1alpha1_RunnerList(in, out, s)
}

func autoConvert_v1alpha1_RunnerSpec_To_v1beta1_RunnerSpec(in *RunnerSpec, out *v1beta1.RunnerSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_RunnerSpec_To_v1beta1_RunnerSpec is an autogenerated conversion function.
func Convert_v1alpha1_RunnerSpec_To_v1beta1_RunnerSpec(in *RunnerSpec, out *v1beta1.RunnerSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RunnerSpec_To_v1beta1_RunnerSpec(in, out, s)
}

func autoConvert_v1beta1_RunnerSpec_To_v1alpha1_RunnerSpec(in *v1beta1.RunnerSpec, out *RunnerSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_RunnerSpec_To_v1alpha1_RunnerSpec is an autogenerated conversion function.
func Convert_v1beta1_RunnerSpec_To_v1alpha1_RunnerSpec(in *v1beta1.RunnerSpec, out *RunnerSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RunnerSpec_To_v1alpha1_RunnerSpec(in, out, s)
}

func autoConvert_v1alpha1_RunnerStatus_To_v1beta1_RunnerStatus(in *RunnerStatus, out *v1beta1.RunnerStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.ProviderID = in.ProviderID
	out.AgentID = in.AgentID
	out.Name = in.Name
	out.OSType = params.OSType(in.OSType)
	out.OSName = in.OSName
	out.OSVersion = in.OSVersion
	out.OSArch = params.OSArch(in.OSArch)
	out.Addresses = *(*[]params.Address)(unsafe.Pointer(&in.Addresses))
	out.Status = params.InstanceStatus(in.Status)
	out.InstanceStatus = garmparams.RunnerStatus(in.InstanceStatus)
	out.PoolID = in.PoolID
	out.ProviderFault = in.ProviderFault
	out.GitHubRunnerGroup = in.GitHubRunnerGroup
	return nil
}

// Convert_v1alpha1_RunnerStatus_To_v1beta1_RunnerStatus is an autogenerated conversion function.
func Convert_v1alpha1_RunnerStatus_To_v1beta1_RunnerStatus(in *RunnerStatus, out *v1beta1.RunnerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RunnerStatus_To_v1beta1_RunnerStatus(in, out, s)
}

func autoConvert_v1beta1_RunnerStatus_To_v1alpha1_RunnerStatus(in *v1beta1.RunnerStatus, out *RunnerStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.ProviderID = in.ProviderID
	out.AgentID = in.AgentID
	out.Name = in.Name
	out.OSType = params.OSType(in.OSType)
	out.OSName = in.OSName
	out.OSVersion = in.OSVersion
	out.OSArch = params.OSArch(in.OSArch)
	out.Addresses = *(*[]params.Address)(unsafe.Pointer(&in.Addresses))
	out.Status = params.InstanceStatus(in.Status)
	out.InstanceStatus = garmparams.RunnerStatus(in.InstanceStatus)
	out.PoolID = in.PoolID
	out.ProviderFault = in.ProviderFault
	out.GitHubRunnerGroup = in.GitHubRunnerGroup
	return nil
}

// Convert_v1beta1_RunnerStatus_To_v1alpha1_RunnerStatus is an autogenerated conversion function.
func Convert_v1beta1_RunnerStatus_To_v1alpha1_RunnerStatus(in *v1beta1.RunnerStatus, out *RunnerStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_RunnerStatus_To_v1alpha1_RunnerStatus(in, out, s)
}

func autoConvert_v1alpha1_SecretRef_To_v1beta1_SecretRef(in *SecretRef, out *v1beta1.SecretRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1alpha1_SecretRef_To_v1beta1_SecretRef is an autogenerated conversion function.
func Convert_v1alpha1_SecretRef_To_v1beta1_SecretRef(in *SecretRef, out *v1beta1.SecretRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecretRef_To_v1beta1_SecretRef(in, out, s)
}

func autoConvert_v1beta1_SecretRef_To_v1alpha1_SecretRef(in *v1beta1.SecretRef, out *SecretRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1beta1_SecretRef_To_v1alpha1_SecretRef is an autogenerated conversion function.
func Convert_v1beta1_SecretRef_To_v1alpha1_SecretRef(in *v1beta1.SecretRef, out *SecretRef, s conversion.Scope) error {
	return autoConvert_v1beta1_SecretRef_To_v1alpha1_SecretRef(in, out, s)
}
