kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/component: metrics
  name: kube-state-metrics-config
  namespace: system
data:
  config.yaml: |
    kind: CustomResourceStateMetrics
    spec:
      resources:
        ##################
        #   ENTERPRISE   #
        #################
        - groupVersionKind:
            group: garm-operator.mercedes-benz.com
            kind: "Enterprise"
            version: "v1beta1"
          metricNamePrefix: garm_operator
          commonLabels:
            crd_type: "enterprise"
          labelsFromPath:
            name: [ metadata, name ]
            namespace: [ metadata, namespace ]
          metrics:
            - name: enterprise_created
              help: Unix creation timestamp.
              each:
                gauge:
                  path:
                    - metadata
                    - creationTimestamp
                type: Gauge

            - name: enterprise_info
              help: Information about an enterprise.
              each:
                type: Info
                info:
                  labelsFromPath:
                    credentialsRefName: [ spec, credentialsRef, name ]
                    webhookSecretRefKey: [ spec, webhookSecretRef, key ]
                    webhookSecretRefName: [ spec, webhookSecretRef, name ]
                    id: [ status, id ]
            
            - name: enterprise_annotation_paused_info
              help: Whether the enterprise reconciliation is paused.
              each:
                type: Info
                info:
                  path:
                    - metadata
                    - annotations
                    - garm-operator.mercedes-benz.com/paused
                  labelsFromPath:
                    paused_value: []

            - name: enterprise_status_conditions
              help: Displays whether status of each possible condition is True or False.
              each:
                type: Gauge
                gauge:
                  path:
                    - status
                    - conditions
                  valueFrom:
                    - status
                  labelFromKey: reason
                  labelsFromPath:
                    type: [ type ]

        ##################
        #   Org         #
        #################
        - groupVersionKind:
            group: garm-operator.mercedes-benz.com
            kind: "Organization"
            version: "v1beta1"
          metricNamePrefix: garm_operator
          commonLabels:
            crd_type: "organization"
          labelsFromPath:
            name: [ metadata, name ]
            namespace: [ metadata, namespace ]
          metrics:
            - name: org_created
              help: Unix creation timestamp.
              each:
                gauge:
                  path:
                    - metadata
                    - creationTimestamp
                type: Gauge

            - name: org_info
              help: Information about an organization.
              each:
                type: Info
                info:
                  labelsFromPath:
                    credentialsRefName: [ spec, credentialsRef, name ]
                    webhookSecretRefKey: [ spec, webhookSecretRef, key ]
                    webhookSecretRefName: [ spec, webhookSecretRef, name ]
                    id: [ status, id ]
            
            - name: org_annotation_paused_info
              help: Whether the org reconciliation is paused.
              each:
                type: Info
                info:
                  path:
                    - metadata
                    - annotations
                    - garm-operator.mercedes-benz.com/paused
                  labelsFromPath:
                    paused_value: [ ]

            - name: org_status_conditions
              help: Displays whether status of each possible condition is True or False.
              each:
                type: Gauge
                gauge:
                  path:
                    - status
                    - conditions
                  valueFrom:
                    - status
                  labelFromKey: reason
                  labelsFromPath:
                    type: [ type ]

        ##################
        #   Repo         #
        #################
        - groupVersionKind:
            group: garm-operator.mercedes-benz.com
            kind: "Repository"
            version: "v1beta1"
          metricNamePrefix: garm_operator
          commonLabels:
            crd_type: "repository"
          labelsFromPath:
            name: [ metadata, name ]
            namespace: [ metadata, namespace ]
          metrics:
            - name: repo_created
              help: Unix creation timestamp.
              each:
                gauge:
                  path:
                    - metadata
                    - creationTimestamp
                type: Gauge

            - name: repo_info
              help: Information about a repository.
              each:
                type: Info
                info:
                  labelsFromPath:
                    owner: [ spec, owner ]
                    credentialsRefName: [ spec, credentialsRef, name ]
                    webhookSecretRefKey: [ spec, webhookSecretRef, key ]
                    webhookSecretRefName: [ spec, webhookSecretRef, name ]
                    id: [ status, id ]
            
            - name: repo_annotation_paused_info
              help: Whether the repo reconciliation is paused.
              each:
                type: Info
                info:
                  path:
                    - metadata
                    - annotations
                    - garm-operator.mercedes-benz.com/paused
                  labelsFromPath:
                    paused_value: [ ]

            - name: repo_status_conditions
              help: Displays whether status of each possible condition is True or False.
              each:
                type: Gauge
                gauge:
                  path:
                    - status
                    - conditions
                  valueFrom:
                    - status
                  labelFromKey: reason
                  labelsFromPath:
                    type: [ type ]

        ##################
        #      Pool     #
        #################
        - groupVersionKind:
            group: garm-operator.mercedes-benz.com
            kind: "Pool"
            version: "v1beta1"
          metricNamePrefix: garm_operator
          commonLabels:
            crd_type: "pool"
          labelsFromPath:
            name: [ metadata, name ]
            namespace: [ metadata, namespace ]
          metrics:
            - name: pool_created
              help: Unix creation timestamp.
              each:
                gauge:
                  path:
                    - metadata
                    - creationTimestamp
                type: Gauge
            
            - name: pool_info
              help: Information about a pool.
              each:
                type: Info
                info:
                  labelsFromPath:
                    githubRunnerGroup: [spec, githubRunnerGroup]
                    scopeKind: [spec, githubScopeRef, kind]
                    scopeName: [spec, githubScopeRef, name]
                    imageName: [spec, imageName]
                    osArch: [spec, osArch]
                    osType: [spec, osType]
                    providerName: [spec, providerName]
                    runnerBootstrapTimeout: [spec, runnerBootstrapTimeout]
                    runnerPrefix: [spec, runnerPrefix]
                    tags: [spec, tags]
                    id: [status, id]

            - name: pool_enabled
              help: Whether the pool is enabled.
              each:
                type: Gauge
                gauge:
                  nilIsZero: true
                  path:
                    - spec
                    - enabled

            - name: pool_min_idle_runners
              help: Minimum number of idle runners.
              each:
                type: Gauge
                gauge:
                  path:
                    - spec
                    - minIdleRunners
                  
            - name: pool_max_runners
              help: Maximum number of runners.
              each:
                type: Gauge
                gauge:
                  path:
                    - spec
                    - maxRunners
            
            - name: status_long_running_idle_runners
              help: Number of long running idle runners.
              each:
                type: Gauge
                gauge:
                  path:
                    - status
                    - longRunningIdleRunners
            
            - name: pool_annotation_paused_info
              help: Whether the pool reconciliation is paused.
              each:
                type: Info
                info:
                  path:
                    - metadata
                    - annotations
                    - garm-operator.mercedes-benz.com/paused
                  labelsFromPath:
                    paused_value: [ ]

            - name: pool_status_conditions
              help: Displays whether status of each possible condition is True or False.
              each:
                type: Gauge
                gauge:
                  path:
                    - status
                    - conditions
                  valueFrom:
                    - status
                  labelFromKey: reason
                  labelsFromPath:
                    type: [ type ]

        ##################
        #      Image    #
        #################
        - groupVersionKind:
            group: garm-operator.mercedes-benz.com
            kind: "Image"
            version: "v1beta1"
          metricNamePrefix: garm_operator
          commonLabels:
            crd_type: "image"
          labelsFromPath:
            name: [ metadata, name ]
            namespace: [ metadata, namespace ]
          metrics:
            - name: image_created
              help: Unix creation timestamp.
              each:
                gauge:
                  path:
                    - metadata
                    - creationTimestamp
                type: Gauge
            
            - name: image_info
              help: Information about an image.
              each:
                type: Info
                info:
                  labelsFromPath:
                    tag: [spec, tag]

        ############################
        #      GarmServerConfig    #
        ############################
        - groupVersionKind:
            group: garm-operator.mercedes-benz.com
            kind: "GarmServerConfig"
            version: "v1beta1"
          metricNamePrefix: garm_operator
          commonLabels:
            crd_type: "garmserverconfig"
          labelsFromPath:
            name: [ metadata, name ]
            namespace: [ metadata, namespace ]
          metrics:
            - name: garmserverconfig_created
              help: Unix creation timestamp.
              each:
                gauge:
                  path:
                    - metadata
                    - creationTimestamp
                type: Gauge
            
            - name: garmserverconfig_info
              help: Information about a garm server config.
              each:
                type: Info
                info:
                  labelsFromPath:
                    callbackUrl: [spec, callbackUrl]
                    metadataUrl: [spec, metadataUrl]
                    webhookUrl: [spec, webhookUrl]
                    controllerId: [status, controllerId]
                    minimumJobAgeBackoff: [status, minimumJobAgeBackoff]
                    version: [status, version]

        ############################
        #      GitHubEndpoint    #
        ############################
        - groupVersionKind:
            group: garm-operator.mercedes-benz.com
            kind: "GitHubEndpoint"
            version: "v1beta1"
          metricNamePrefix: garm_operator
          commonLabels:
            crd_type: "githubendpoint"
          labelsFromPath:
            name: [ metadata, name ]
            namespace: [ metadata, namespace ]
          metrics:
            - name: githubendpoint_created
              help: Unix creation timestamp.
              each:
                gauge:
                  path:
                    - metadata
                    - creationTimestamp
                type: Gauge
            
            - name: githubendpoint_info
              help: Information about a githubendpoint config.
              each:
                type: Info
                info:
                  labelsFromPath:
                    apiBaseUrl: [spec, apiBaseUrl]
                    baseUrl: [spec, baseUrl]
                    uploadBaseUrl: [spec, uploadBaseUrl]

            - name: githubendpoint_status_conditions
              help: Displays whether status of each possible condition is True or False.
              each:
                type: Gauge
                gauge:
                  path:
                    - status
                    - conditions
                  valueFrom:
                    - status
                  labelFromKey: reason
                  labelsFromPath:
                    type: [ type ]

        ############################
        #      GitHubCredential    #
        ############################
        - groupVersionKind:
            group: garm-operator.mercedes-benz.com
            kind: "GitHubCredential"
            version: "v1beta1"
          metricNamePrefix: garm_operator
          commonLabels:
            crd_type: "githubcredential"
          labelsFromPath:
            name: [ metadata, name ]
            namespace: [ metadata, namespace ]
          metrics:
            - name: githubcredential_created
              help: Unix creation timestamp.
              each:
                gauge:
                  path:
                    - metadata
                    - creationTimestamp
                type: Gauge
            
            - name: githubcredential_info
              help: Information about a githubcredential config.
              each:
                type: Info
                info:
                  labelsFromPath:
                    authType: [spec, authType]
                    secretRefKey: [ spec, secretRef, key ]
                    secretRefName: [ spec, secretRef, name ]
                    endpointRefName: [ spec, endpointRef, name ]
                    apiBaseUrl: [status, apiBaseUrl]
                    baseUrl: [status, baseUrl]
                    uploadBaseUrl: [status, uploadBaseUrl]
                    id: [status, id]

            - name: githubcredential_status_conditions
              help: Displays whether status of each possible condition is True or False.
              each:
                type: Gauge
                gauge:
                  path:
                    - status
                    - conditions
                  valueFrom:
                    - status
                  labelFromKey: reason
                  labelsFromPath:
                    type: [ type ]
