{{- if .Values.webhook.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "garm-operator.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "garm-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      protocol: TCP
      targetPort: {{ .Values.webhook.port }}
  selector:
    {{- include "garm-operator.selectorLabels" . | nindent 4 }}
{{- end }}
