{{- if and .Values.garm.password (not .Values.garm.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garm-operator.fullname" . }}-garm-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "garm-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.garm.secretKeys.passwordKey }}: {{ .Values.garm.password | quote }}
  {{- if .Values.garm.username }}
  {{ .Values.garm.secretKeys.usernameKey }}: {{ .Values.garm.username | quote }}
  {{- end }}
  {{- if .Values.garm.server }}
  {{ .Values.garm.secretKeys.serverKey }}: {{ .Values.garm.server | quote }}
  {{- end }}
{{- end }}
