# SPDX-License-Identifier: MIT

name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod

      - name: make verify
        run: make verify

      - name: make lint
        run: make golangci-lint && GOLANGCI_LINT_EXTRA_ARGS=--timeout=1h make lint

      - name: make test
        run: make test

      - name: make sbom
        run: make sbom

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sbom
          path: tmp/garm-operator.bom.spdx
