name: test and lint
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: lint and test
    runs-on: [ road-runner, small ] # could run on a k8s pod in the future
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: make lint
        run: GOLANGCI_LINT_EXTRA_ARGS=--timeout=1h make lint
      
      - name: make test
        run: make test
